config/routes.rb
Rails.application.routes.draw do
	devise_for :users
	
	resources :users, :only => [:show]

	get 'users/:id/follow' => 'users#follow', as: 'follow'
	get 'users/:id/unfollow' => 'users#unfollow', as: 'unfollow'

	root 'posts#index'
	
	resources :posts do
		resources :likes, :only => [:create, :destroy]
		resources :comments, :only => [:create]
	end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/follower.rb
class Follower < ApplicationRecord
  belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many_attached :images
  has_many :likes, dependent: :destroy
  has_many :comments

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable
  
  validates :name, presence: true, length: { maximum: 50 }
  has_one_attached :avatar

  has_many :posts
  has_many :likes, dependent: :destroy
  has_many :comments
  has_many :followers, dependent: :destroy


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	 # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  
  private
  
  def configure_permitted_parameters
  	devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  	devise_parameter_sanitizer.permit(:sign_up, keys: [:avatar])
  	devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  	devise_parameter_sanitizer.permit(:account_update, keys: [:avatar])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
   def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)

    redirect_to @post
  end

  private

  def comment_params
    params.require(:comment).permit(:user_id, :body)
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
	before_action :find_post
	before_action :find_like, only: [:destroy] 

	def create
		if already_liked?
			flash[:notice] = "You can't like more than once"
		else
			@post.likes.create(user_id: current_user.id)
		end
		redirect_back(fallback_location: request.referer)
	end

	def destroy
		if !(already_liked?)
			flash[:notice] = "Cannot unlike"
		else
			@like.destroy
		end
		redirect_back(fallback_location: request.referer)
	end

	private

	def already_liked?
		Like.where(user_id: current_user.id, post_id:
			params[:post_id]).exists?
	end

	def find_post
		@post = Post.find(params[:post_id])
	end

	def find_like
		@like = @post.likes.find(params[:id])
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :set_post, only: [:show, :edit, :update, :destroy]

	def index
		@posts = Post.order(created_at: :desc)
	end

	def show
	end

	def new
		@post = Post.new
	end

	def edit
	end


	def create
		@post = Post.new(post_params)
		@post.user_id = current_user.id
		@post.images.attach(params[:post][:images])

		respond_to do |format|
			if @post.save
				format.html { redirect_to @post, notice: 'Post was successfully created.' }
				format.json { render :show, status: :created, location: @post }
			else
				format.html { render :new }
				format.json { render json: @post.errors, status: :unprocessable_entity }
			end
		end
	end

	def update
		respond_to do |format|
			if @post.update(post_params)
				format.html { redirect_to @post, notice: 'Post was successfully updated.' }
				format.json { render :show, status: :ok, location: @post }
			else
				format.html { render :edit }
				format.json { render json: @post.errors, status: :unprocessable_entity }
			end
		end
	end

	def destroy
		@post.destroy
		respond_to do |format|
			format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
			format.json { head :no_content }
		end
	end

	private
	def set_post
		@post = Post.find(params[:id])
	end

	def post_params
		params.require(:post).permit(:title, :images)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find(params[:id])
  	@posts = Post.all
  end

  def follow
  	@user = User.find(params[:id])
  	
    if current_user.id == @user.id
      redirect_to user_path(@user), notice: 'Вы не можете подписаться на себя'
    else
      if current_user.followers.exists?(friend_id: @user.id)
        redirect_to user_path(@user), notice: 'Вы подписаны на этого пользователя'
      else
        @follow = current_user.followers.build
        @follow.friend_id = @user.id

        if @follow.save
          redirect_to user_path(@user), notice: 'Вы подписаны на этого пользователя'
        end
      end
    end
  end

  def unfollow
  	@user = User.find(params[:id])
    if current_user.id == @user.id
      redirect_to user_path(@user), notice: 'Вы не можете подписаться на себя'
    else
      if current_user.followers.exists?(friend_id: @user.id)
        @follow = current_user.followers.find_by(friend_id: @user.id)
        @follow.destroy
        redirect_to user_path(@user), notice: 'Вы больше не подписаны на этого пользователя'
      else
        redirect_to user_path(@user), notice: 'Вы не были подписаны на этого пользователя'
      end
    end
  end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<li>
  <p>
    <strong><%= comment.user.name %></strong> said:
  </p>
  <p>
    <%= comment.body %>
  </p>
</li>

app/views/comments/_form.html.erb
<%= form_with scope: :comment, url: [@post, @post.comments.build] do |f| %>
    <div>
      <%= f.hidden_field :user_id, value: current_user.id %>
    </div>
    <div>
      Text: <%= f.text_area :body %>
    </div>

    <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Homework66</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<%= render 'layouts/application/navbar' %>

<body>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  
  <%= yield %>
</body>
</html>

app/views/layouts/application/_navbar.html.erb
<nav class="navbar fixed-top navbar-dark bg-dark navbar-expand-md">
    <div class="container">
        <button type="button" class="navbar-toggler collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          &#x2630;
      </button>

      <%= link_to 'Home', root_path, class: 'navbar-brand' %>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
            <li class="nav-item"><%= link_to "My profile", current_user, class: "nav-link" %></a>
            </li>
        </ul>
        <div class="navbar-nav ml-auto">
          <div class="navbar-nav ml-auto">
              <% if user_signed_in? %>

              <div class="nav-item">
                <span class="navbar-text">
                  Hello, &nbsp;
                  <span>
                  </div>

                  <div class="dropdown show">
                    <%= link_to current_user.name, edit_user_registration_path(current_user), class: 'btn btn-secondary dropdown-toggle', 'role' => "button", 'id' => "dropdownMenuLink", 'data-toggle' => "dropdown", 'aria-haspopup' => "true", 'aria-expanded' => "false" %>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                      <%= link_to 'Edit profile', edit_user_registration_path(current_user), class: 'dropdown-item' %>
                      <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
                  </div>
                  <div>



                    <% else %>
                    <div class="nav-item">
                       <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
                   </div>
                   <div class="nav-item">
                       <%= link_to 'Log in', new_user_session_path, class: 'nav-link' %>
                   </div>
                   <% end %>
               </div>
           </div>
       </div>
   </div>
</nav>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
<% if post.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

  <ul>
    <% post.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= form.label :title %>
  <%= form.text_field :title %>
</div>

<div>
  <%= form.label :images %>
  <%= form.file_field :images, multiple: true %>
</div>

<div class="actions">
  <%= form.submit %>
</div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <h1>All Posts</h1>


  <div>
    <% @posts.each do |post| %>
    
        <p><b>Title:</b><%= link_to post.title, post_path(post.id), class: 'btn btn-warning' %></p>
        <p>
          <% if post.images.attached? %>
            <% post.images.each do |image| %>
            <%= image_tag image, size: 300 %>
            <% end %>
          <% end %>
        </p>
        <p><b>User:</b><%= link_to post.user.name, user_path(post.user), class: 'btn btn-success' %></p>

      <% if user_signed_in? %>   
        <% pre_like = post.likes.find { |like| like.user == current_user} %>
        <% if pre_like %>
          <%= button_to 'Unlike', post_like_path(post, pre_like), method: :delete %>
          <% else %>
          <%= button_to 'Like', post_likes_path(post), method: :post %>
        <% end %>
      <% end %>

      <p><%= post.likes.count %> <%= (post.likes.count) == 1 ? 'Like' : 'Likes'%></p>

    <% end %>

  </div>
  

</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
	<strong>Title:</strong>
	<%= @post.title %>
</p>
<p>
<% if @post.images.attached? %>
	<% @post.images.each do |image| %>
	<%= image_tag image, size: 300 %>
	<% end %>
	<% end %>
</p>

<p>
	<strong>User:</strong>
	<%= @post.user.name%>
</p>
<% if current_user.id == @post.user.id %>
<%= link_to 'Edit', edit_post_path(@post) %> 
<% end %>

<h2><%= link_to 'Comments', '#', id: 'comments-link' %></h2>
<div id="comment-section">
	<ol id="comments">
		<%= render @post.comments %>
	</ol>

	<h3>Add a comment:</h3>
	<%= render 'comments/form' %>
</div>

app/views/users/show.html.erb
<div class="container">
	<p id="notice"><%= notice %></p>

	<%= link_to 'New Post', new_post_path, class: "btn btn-primary" %><br>

	<% if @user.avatar.attached? %>
	<%= image_tag @user.avatar, size: 250 %>
	<% end %>
	<h1><%= @user.name %></h1><br>
	<p><%= @user.email %></p>

	<% if current_user.id != @user.id %>
		<% if Follower.where(user_id: current_user).exists? %>
			<%= link_to 'Unfollow', unfollow_path(@user), class: 'btn btn-sm btn-info' %>
		<% else %>
			<%= link_to 'Following', follow_path(@user), class: 'btn btn-sm btn-info' %>
		<% end %>
	<% end %>

	<h1>My Posts</h1>

	<table>
		<thead>
			<tr>
				<th>Title</th>
				<th>Images</th>
				<th colspan="3"></th>
			</tr>
		</thead>

		<tbody>
			<% @user.posts.each do |post| %>
			<tr>
				<td><%= post.title %></td>
				<td>
					<% if post.images.attached? %>
					<% post.images.each do |image| %>
					<%= image_tag image, size: 300 %>
					<% end %>
					<% end %>
				</td>
				<td><%= link_to 'Show', post %></td>
				<td><%= link_to 'Edit', edit_post_path(post) %></td>
				<td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
			</tr>
			<% end %>
		</tbody>
	</table>

	<br>

</div>